template
Signed-off-by: zenobit <zenobit@disroot.org>

diff --git a/quickget_plugins/template b/quickget_plugins/template
--- a/quickget_plugins/template
+++ b/quickget_plugins/template
@@ -1,16 +1,16 @@
 #!/usr/bin/bash
-#
+
 #   This template identifies the functions required to supported by each OS
 
+# Use this function to override the standard function in quickget
+# if you distribution requires something special. Windows and Mac are examples..
 #function create_vm() {
-#    #    This function can be used to over rid the standard function in quickget 
-#     #    if you distribution requires something special. Windows and Mac are examples
-#    #    that will need to provide this function
+#
 #}
 
+# This function returns an associative array with keys "url", "iso", and "hash"
+# Change this function for your distro
 function get_distro_info() {
-    #   This function returns an associative array with keys "url", "iso", and "hash"
-    #   You WILL HAVE to change this functiion for your distro
     declare -A distro_info
     distro_info['url']="https://repo.almalinux.org/almalinux/${RELEASE}/isos/x86_64"
     distro_info['iso']="AlmaLinux-${RELEASE}-latest-x86_64-${EDITION}.iso"
@@ -21,25 +21,49 @@ function get_distro_info() {
     done
 }
 
-#function get_file() {
-#    #    This function can be used to over rid the standard function in quickget 
-#    #    if you distribution requires something special. Windows and Mac are examples
-#    #    that will need to provide this function
-#}
+# Use this function to override the standard function in quickget
+# if you distribution requires something special. Windows and Mac are examples..
+function get_file() {
+    local url=${1}
+    local dir=${2}
+    local file=${3}
 
-function releases() {
-    #   This funciton returns supported OS releases for the OS
-    #   You WILL HAVE to change this functiion for your distro
-    echo 8 9
+    if [ -z "${file}" ]; then
+        file="${url##*/}"
+    fi
+
+    if command -v aria2c &>/dev/null; then
+        echo aria2c
+        if ! aria2c --stderr -x16 --continue=true --summary-interval=0 --download-result=hide --console-log-level=error "${url}" --dir "${dir}" -o "${file}"; then
+          echo #Necessary as aria2c in suppressed mode does not have new lines
+          error "Failed to download ${URL} with aria2c. Try running 'quickget' again."
+          exit 1
+        fi
+        echo #Necessary as aria2c in suppressed mode does not have new lines
+    elif ! wget --quiet --continue --tries=3 --read-timeout=10 --show-progress --progress=bar:force:noscroll "${url}" -O "${dir}/${file}"; then
+        error "Failed to download ${URL} with wget. Try running 'quickget' again."
+        exit 1
+    fi
+
+    if [[ ${DISTRO_INFO['iso']} =~ .gz ]]; then
+        gzip -d "${VM_PATH}/${DISTRO_INFO['iso']}"
+        DISTRO_INFO['iso']="${DISTRO_INFO['iso']/.gz/}"
+    fi
 }
 
+# This funciton returns supported OS releases for the OS
+# Change this function for your distro
+function releases() {
+    echo latest
+}
+
+# This function returns an associative array with releases as the key
+# and a "!" separated string of valid editions for the specific release.
+# While quite often editions are the same for all releases it is not always
+# the case.
+# Editions have different meanings for different OS's
+# Change this function for your distro
 function editions() {
-    #   This frunctions returns sn associative array with releases as the key
-    #   and a "!" seperated string of valid editions for the specific release.
-    #   While quite often editions are the same for all releases it is not always
-    #   the case.
-    #   Editions have different meanings for different OS's
-    #   You WILL HAVE to change this functiion for your distro
     declare -A editions
     local release
 
@@ -52,31 +76,34 @@ function editions() {
     done
 }
 
+# Change this function for your distro
+# Returning 0 means editions are required and 1 not required
 function editions_required() {
-    #   You WILL HAVE to change this functiion for your distro
-    return 0        # Returning 0 means editions requuuuuire and 1 is not required
+    return 0
 }
 
+# This function returns an expanded OS name for pretty printing
+# Change this function for your distro
 function pretty_name() {
-    #   This funcction returns an expanded OS name for pretty printing
-    #   You WILL HAVE to change this functiion for your distro
     echo "Alma Linux"
 }
 
+# This function returns the OS's home page URL
+# Change this function for your distro
 function homepage() {
-    #   This function returns the OS's home page URL
-    #   You WILL HAVE to change this functiion for your distro
     echo "https://almalinux.org/"
 }
 
+# This function creates the vm_config file and can be used to
+# replace the default one in the quickget
+# Change this function for your distro
 function make_vm_config() {
-    #   This function creates the vm_config file and can be used to
-    #   replace the default one in the quickget
-    #   You MIGHT HAVE to change this functiion for your distro
     default_vm_config
 
     # Override any default settings
-    # i.e sed -i 's/^disk_size=.*/disk_size=\"80G\"/' "${VM_PATH}".conf
+    sed -i 's/guest_os=.*/guest_os="batocera"/' "${VM_PATH}".conf
+    sed -i 's/^disk_size=.*/disk_size=\"80G\"/' "${VM_PATH}".conf
+    sed -i 's/iso=/img=/' "${VM_PATH}".conf
 
     # Add any additional lines
     # {
