feat: handle_missing

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3552,6 +3552,26 @@ os_supported_lang() {
     exit 1
 }
 
+handle_missing() {
+    # Handle odd missing Fedora combinations
+    if [[ $OS == fedora ]] ; then
+        if [[ ${RELEASE} = "33" && ${EDITION} = "i3" ]] || [[ ${RELEASE} = "34" && ${EDITION} = "Cinnamon" ]] || [[ "${RELEASE}" < "39" && ${EDITION} = "Onyx" ]]; then
+            echo "ERROR! Unsupported combination"
+            echo "       Fedora ${RELEASE} ${EDITION} is not available, please choose another Release or Edition"
+            exit 1;
+        fi
+    fi
+
+    # Handle missing Manjaro Sway minimal
+    if [[ $OS == manjaro ]] ; then
+        if [[ ${RELEASE} == "sway" && ${EDITION} == "minimal" ]] ; then
+            echo "ERROR! Unsupported combination"
+            echo "       Manjaro Sway does not have a minimal edition"
+            exit 1;
+        fi
+    fi
+}
+
 function show_os_info() {
     local OS=""
     if [ -z "${1}" ]; then
@@ -3671,23 +3691,7 @@ if [ -n "${2}" ]; then
             os_error_edition
         fi
 
-        # Handle odd missing fedora cominations
-        if [[ $OS == fedora ]] ; then
-            if [[ ${RELEASE} = "33" && ${EDITION} = "i3" ]] || [[ ${RELEASE} = "34" && ${EDITION} = "Cinnamon" ]] || [[ "${RELEASE}" < "39" && ${EDITION} = "Onyx" ]]; then
-                echo "ERROR! Unsupported combination"
-                echo "       Fedora ${RELEASE} ${EDITION} is not available, please choose another Release or Edition"
-                exit 1;
-            fi
-        fi
-
-        # Handle missing Mangaro Sway minimal
-        if [[ $OS == manjaro ]] ; then
-            if [[ ${RELEASE} == "sway" && ${EDITION} == "minimal" ]] ; then
-                echo "ERROR! Unsupported combination"
-                echo "       Manjaro Sway does not have a minimal edition"
-                exit 1;
-            fi
-        fi
+        handle_missing
 
         VM_PATH="${OS}-${RELEASE}-${EDITION}"
         create_vm "$("get_${OS}" "${EDITION}")"
