feat: os_error_release

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3494,6 +3494,36 @@ os_not_supported() {
     exit 1
 }
 
+os_error_release() {
+    echo "ERROR! You must specify a release."
+    case ${OS} in
+      *ubuntu-server*)
+        echo -n " - Releases: "
+        releases_ubuntu-server | sed -Ee 's/eol-\S+//g' # hide eol releases
+        ;;
+      *ubuntu*)
+        echo -n " - Releases: "
+        releases_ubuntu | sed -Ee 's/eol-\S+//g' # hide eol releases
+        ;;
+      *windows*)
+        echo -n " - Releases: "
+        "releases_${OS}"
+        echo -n " - Languages: "
+        "languages_${OS}" && echo "${LANGS[@]}"
+        ;;
+      *)
+        if [[ $(type -t "editions_${OS}") == function ]]; then
+            echo -n ' - Editions: '
+            "editions_${OS}"
+        else
+            echo -n " - Releases: "
+            "releases_${OS}" | fold -s -w "$(tput cols)"
+        fi
+        ;;
+    esac
+    exit 1
+}
+
 function show_os_info() {
     local OS=""
     if [ -z "${1}" ]; then
@@ -3684,32 +3714,7 @@ elif [ $(releases_"${OS}" | wc -w) -eq 1 ] && [[ ! $(type -t "editions_${OS}") =
     VM_PATH="${OS}"
     create_vm "$("get_${OS}")"
 else
-    echo "ERROR! You must specify a release."
-    case ${OS} in
-      *ubuntu-server*)
-        echo -n " - Releases: "
-        releases_ubuntu-server | sed -Ee 's/eol-\S+//g' # hide eol releases
-        ;;
-      *ubuntu*)
-        echo -n " - Releases: "
-        releases_ubuntu | sed -Ee 's/eol-\S+//g' # hide eol releases
-        ;;
-      *windows*)
-        echo -n " - Releases: "
-        "releases_${OS}"
-        echo -n " - Languages: "
-        "languages_${OS}" && echo "${LANGS[@]}"
-        ;;
-      *)
-      echo -n " - Releases: "
-      "releases_${OS}" | fold -s -w "$(tput cols)"
-        if [[ $(type -t "editions_${OS}") == function ]]; then
-          echo -n " - Editions: "
-          editions_"${OS}" | fold -s -w "$(tput cols)"
-        fi
-        ;;
-    esac
-    exit 1
+    os_error_release
 fi
 
 # vim:tabstop=4:shiftwidth=4:expandtab
