windows d/l  upd - change two html vars to json

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3132,10 +3132,10 @@ function download_windows_workstation() {
     local iso_download_page_html=""
     local product_edition_id=""
     local language_skuid_table_cmd=""
-    local language_skuid_table_html=""
+    local language_skuid_table_json=""
     local sku_id=""
     local iso_download_link_cmd=""
-    local iso_download_link_html=""
+    local iso_download_link_json=""
     local iso_download_link=""
 
     echo; echo "Downloading Windows ${RELEASE} (${I18N})"; echo
@@ -3218,27 +3218,27 @@ function download_windows_workstation() {
     # SKU ID: This specifies the language of the ISO. We always use "English (United States)", however, the SKU for this changes with each Windows release
     # We must make this request so our next one will be allowed
     # --data "" is required otherwise no "Content-Length" header will be sent causing HTTP response "411 Length Required"
-    language_skuid_table_html="$(curl --silent --request POST --user-agent "$user_agent" --data "" --header "Accept:" --max-filesize 10K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=getskuinformationbyproductedition&sessionId=$session_id&productEditionId=$product_edition_id&sdVersion=2")" || {
+    language_skuid_table_json="$(curl --silent --request POST --user-agent "$user_agent" --data "" --header "Accept:" --max-filesize 10K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=getskuinformationbyproductedition&sessionId=$session_id&productEditionId=$product_edition_id&sdVersion=2")" || {
         handle_curl_error $?
         return $?
     }
 
     language_skuid_table_cmd="$(echo --silent --request POST --user-agent "$user_agent" --data "" --header "Accept:" --max-filesize 10K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=getskuinformationbyproductedition&sessionId=$session_id&productEditionId=$product_edition_id&sdVersion=2")" 
 
-    { echo; date; echo "language_skuid_table_html - FULL "; echo; echo "$language_skuid_table_html"; echo ; echo "End of Page"; echo
+    { echo; date; echo "language_skuid_table_json - FULL "; echo; echo "$language_skuid_table_json"; echo ; echo "End of Page"; echo
     } >  "/tmp/qe_win_dl_lang_table full.txt"
 
     # Limit untrusted size for input validation
-    language_skuid_table_html="$(echo "$language_skuid_table_html" | head -c 10240)"
+    language_skuid_table_json="$(echo "$language_skuid_table_json" | head -c 10240)"
 
     { echo "language_skuid_table_cmd"; echo; echo "curl $language_skuid_table_cmd"; echo 
     } >>  "/tmp/qe_win_dl_log.txt"
 
-    { echo "language_skuid_table_html"; echo; echo "$language_skuid_table_html"; echo 
+    { echo "language_skuid_table_json"; echo; echo "$language_skuid_table_json"; echo 
     } >>  "/tmp/qe_win_dl_log.txt"
 
     # tr: Filter for only alphanumerics or "-" to prevent HTTP parameter injection
-    sku_id="$(echo "$language_skuid_table_html" | grep "${I18N}&" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
+    sku_id="$(echo "$language_skuid_table_json" | grep "${I18N}&" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
     echo "$sku_id"
 
     RndNum="$( (tr -cd '0-4' | head -c 1) < /dev/urandom )"
@@ -3252,7 +3252,7 @@ function download_windows_workstation() {
     # Get ISO download link
     # If any request is going to be blocked by Microsoft it's always this last one (the previous requests always seem to succeed)
     # --referer: Required by Microsoft servers to allow request
-    iso_download_link_html="$(curl --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=GetProductDownloadLinksBySku&sessionId=$session_id&skuId=$sku_id&language=English&sdVersion=2")"
+    iso_download_link_json="$(curl --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=GetProductDownloadLinksBySku&sessionId=$session_id&skuId=$sku_id&language=English&sdVersion=2")"
     iso_download_link_cmd="$(echo --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,${url_segment_parameter}&query=&action=GetProductDownloadLinksBySku&sessionId=${session_id}&skuId=${sku_id}&language=English&sdVersion=2")"
 
     RndNum="$( (tr -cd '2-5' | head -c 1) < /dev/urandom )"
@@ -3261,22 +3261,22 @@ function download_windows_workstation() {
     { echo "iso_download_link_cmd"; echo; echo "curl $iso_download_link_cmd"; echo 
     } >>  "/tmp/qe_win_dl_log.txt"
 
-    { echo "iso_download_link_html"; echo; echo "$iso_download_link_html"; echo 
+    { echo "iso_download_link_json"; echo; echo "$iso_download_link_json"; echo 
     } >>  "/tmp/qe_win_dl_log.txt"
 
     local failed=0
-    if ! [ "$iso_download_link_html" ]; then
+    if ! [ "$iso_download_link_json" ]; then
         # This should only happen if there's been some change to how this API works
         echo; echo " - Microsoft servers gave us an empty response to our request for an automated download."
         failed=1
     fi
 
-    if echo "$iso_download_link_html" | grep -q "We are unable to complete your request at this time."; then
+    if echo "$iso_download_link_json" | grep -q "We are unable to complete your request at this time."; then
         echo; echo " - UNFORTUNATELY: Microsoft blocked the download request based on your IP address."; echo
         failed=1
     fi
 
-    if echo "$iso_download_link_html" | grep -q "We encountered a problem processing your request. Please try again later."; then
+    if echo "$iso_download_link_json" | grep -q "We encountered a problem processing your request. Please try again later."; then
         echo; echo " - UNFORTUNATELY: Microsoft blocked the request and is saying to try again later."; echo
         failed=1
     fi
@@ -3292,7 +3292,7 @@ function download_windows_workstation() {
     # Filter for 64-bit ISO download URL
     # sed: HTML decode "&" character
     # tr: Filter for only alphanumerics or punctuation
-    iso_download_link="$(echo "$iso_download_link_html" | grep -o "https://software.download.prss.microsoft.com.*IsoX64" | cut -d '"' -f 1 | sed 's/&amp;/\&/g' | tr -cd '[:alnum:][:punct:]')"
+    iso_download_link="$(echo "$iso_download_link_json" | grep -o "https://software.download.prss.microsoft.com.*IsoX64" | cut -d '"' -f 1 | sed 's/&amp;/\&/g' | tr -cd '[:alnum:][:punct:]')"
     
     { echo "iso_download_link - filtered"; echo; echo "$iso_download_link"; echo 
     } >>  "/tmp/qe_win_dl_log.txt"
