Add Windows, misc. other changes

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -33,13 +33,12 @@ function handle_urls() {
     fi
 
     local URL=""
-    for URL in "${URLs[@]}"; do
-        check_hash "${URL}" || web_get "${URL}"
+    for URL in ${PLUGIN_OUTPUT}; do
+        check_hash "${URL}" || web_get "${URL}" || FILE="${URL}"
     done
 }
 
 function check_hash() {
-    local FILE=""
     local HASH="${1}"
     local HASH_ALGO=""
 
@@ -73,8 +72,14 @@ function check_hash() {
 }
 
 function web_get() {
-    local FILE="${URL##*/}"
     local URL="${1}"
+    if [ -z "${FILE}" ]; then
+        FILE="${URL##*/}"
+    fi
+
+    if ! echo "${URL}" | grep -q "/"; then
+        return 1
+    fi
 
 	if [ "${TEST_ISO_URL}" == 'true' ]; then
         wget --spider "${URL}"
@@ -107,6 +112,7 @@ function web_get() {
     fi
     # Set the last downloaded filename for use in the check_hash function
     LAST_DOWNLOADED="${VM_PATH}/${FILE}"
+    FILE=""
 }
 
 function list_json() {
@@ -139,6 +145,15 @@ function verify_release() {
     fi
 }
 
+function handle_config_additions() {
+    local CONFIG_ADDITIONS=""
+    CONFIG_ADDITIONS="$("${PLUGIN}" --config-additions)"
+    echo "${CONFIG_ADDITIONS}" | while IFS= read -r CHANGE; do
+        echo "${CHANGE}" >> "${CONF_FILE}"
+        echo "PLACEHOLDER: ${CHANGE}"
+    done
+}
+
 function make_vm_config() {
     CONF_FILE="${VM_PATH}.conf"
     local IMAGE_TYPE=""
@@ -160,6 +175,7 @@ EOF
     echo "Giving user execute permissions on ${CONF_FILE},"
     chmod u+x "${CONF_FILE}"
     fi
+    handle_config_additions
 }
 
 function find_plugin() {
@@ -308,15 +324,25 @@ fi
 VM_DIR="$(pwd)"
 export VM_DIR VM_PATH
 
-read -ra URLs <<<"$("${PLUGIN}" --list-urls --download)"
+PLUGIN_OUTPUT="$("${PLUGIN}" --list-urls --download)"
+EXIT_STATUS="${?}"
 
-if [ "${?}" != 2 ]; then
-    handle_urls
-    if [ -z "${LAST_DOWNLOADED}" ]; then
-        echo "ERROR! Received no URLs from the ${PRETTY_NAME} plugin. Try running 'quickget' again."
-        exit 1
-    fi
-fi
+case "${EXIT_STATUS}" in
+    0)
+        handle_urls
+        if [ -z "${LAST_DOWNLOADED}" ]; then
+            echo "ERROR! Received no URLs from the ${PRETTY_NAME} plugin. Try running 'quickget' again."
+            exit 1
+        fi;;
+    1)
+        echo "${PLUGIN_OUTPUT}"
+        exit 1;;
+esac
+
+prepare_image_output="$("${PLUGIN}" --prepare-image)"
+if echo "${prepare_image_output}" | grep -q "NEW_IMAGE_FILE"; then
+    IMAGE_FILE="${prepare_image_output#*NEW_IMAGE_FILE }"
+fi 
 
 make_vm_config
 
