windows
Signed-off-by: zenobit <zenobit@disroot.org>

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -254,7 +254,8 @@ function list_csv() {
         for OPTION in $(editions_"${OS}"); do
           echo "${DISPLAY_NAME},${OS},${RELEASE},${OPTION},${DOWNLOADER},${PNG},${SVG}"
         done
-      elif [ "${OS}" == "windows" ]; then
+      elif [[ "${OS}" == "windows"* ]]; then
+        "languages_${OS}"
         for OPTION in "${LANGS[@]}"; do
           echo "${DISPLAY_NAME},${OS},${RELEASE},${OPTION},${DOWNLOADER},${PNG},${SVG}"
         done
@@ -461,6 +462,7 @@ function os_support() {
     void \
     vxlinux \
     windows \
+    windows-server \
     xerolinux \
     xubuntu \
     zorin
@@ -962,7 +964,32 @@ function releases_vxlinux() {
 }
 
 function releases_windows() {
-    echo 8 10 11
+    echo 11 10-ltsc 10 8
+}
+
+function languages_windows() {
+    if [ "${RELEASE}" == 8 ]; then
+        LANGS=("Arabic" "Brazilian Portuguese" "Bulgarian" "Chinese (Simplified)" "Chinese (Traditional)" "Chinese (Traditional Hong Kong)" \
+        "Croatian" "Czech" "Danish" "Dutch" "English (United States)" "English International" "Estonian" "Finnish" "French" "German" "Greek" \
+        "Hebrew" "Hungarian" "Italian" "Japanese" "Latvian" "Lithuanian" "Norwegian" "Polish" "Portuguese" "Romanian" "Russian" "Serbian Latin" \
+        "Slovak" "Slovenian" "Spanish" "Swedish" "Thai" "Turkish" "Ukrainian")
+    elif [ "${RELEASE}" == "10-ltsc" ]; then
+        LANGS=("English (United States)" "English (Great Britain)" "Chinese (Simplified)" "Chinese (Traditional)" \
+        "French" "German" "Italian" "Japanese" "Korean" "Portuguese (Brazil)" "Spanish")
+    else
+        LANGS=("Arabic" "Brazilian Portuguese" "Bulgarian" "Chinese (Simplified)" "Chinese (Traditional)" "Croatian" "Czech" "Danish" "Dutch" \
+        "English (United States)" "English International" "Estonian" "Finnish" "French" "French Canadian" "German" "Greek" "Hebrew" "Hungarian" \
+        "Italian" "Japanese" "Korean" "Latvian" "Lithuanian" "Norwegian" "Polish" "Portuguese" "Romanian" "Russian" "Serbian Latin" "Slovak" \
+        "Slovenian" "Spanish" "Spanish (Mexico)" "Swedish" "Thai" "Turkish" "Ukrainian")
+    fi
+}
+
+function releases_windows-server() {
+    echo 2022 2019 2016 2012-r2
+}
+
+function languages_windows-server() {
+    LANGS=("English (United States)" "Chinese (Simplified)" "French" "German" "Italian" "Japanese" "Russian" "Spanish")
 }
 
 function releases_xerolinux() {
@@ -1029,14 +1056,25 @@ function web_get() {
       exit 1
     fi
 
+    if [[ ${OS} != windows && ${OS} != macos && ${OS} != windows-server ]]; then
+        echo Downloading "$(pretty_name "${OS}")" "${RELEASE}" ${EDITION:+ $EDITION} from "${URL}"
+    fi
+
     if command -v aria2c &>/dev/null; then
-        if ! aria2c --stderr -x16 --continue=true --summary-interval=0 --download-result=hide --console-log-level=error "${URL}" --dir "${DIR}" -o "${FILE}"; then
+        if ! aria2c --stderr -x16 --continue=true --summary-interval=0 --download-result=hide --console-log-level=error "${URL}" --dir "${DIR}" -o "${FILE}" "${HEADERS[@]}"; then
           echo #Necessary as aria2c in suppressed mode does not have new lines
           echo "ERROR! Failed to download ${URL} with aria2c. Try running 'quickget' again."
           exit 1
         fi
         echo #Necessary as aria2c in suppressed mode does not have new lines
-    elif ! wget --quiet --continue --tries=3 --read-timeout=10 --show-progress --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}"; then
+    elif command -v wget2 &>/dev/null; then
+
+        if ! wget2 --quiet --continue --tries=3 --read-timeout=10 --force-progress --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}" "${HEADERS[@]}"; then
+            echo "ERROR! Failed to download ${URL} with wget2. Try running 'quickget' again."
+            exit 1
+        fi
+
+    elif ! wget --quiet --continue --tries=3 --read-timeout=10 --show-progress --progress=bar:force:noscroll "${URL}" -O "${DIR}/${FILE}" "${HEADERS[@]}"; then
         echo "ERROR! Failed to download ${URL} with wget. Try running 'quickget' again."
         exit 1
     fi
@@ -1067,6 +1105,7 @@ function zsync_get() {
           exit 1
         fi
 
+        echo -e Downloading "$(pretty_name "${OS}")" "${RELEASE}" ${EDITION+ ${EDITION}} from "${URL}"'\n'
         # Only force http for zsync - not earlier because we might fall through here
         if ! zsync "${URL/https/http}.zsync" -i "${DIR}/${OUT}" -o "${DIR}/${OUT}" 2>/dev/null; then
             echo "ERROR! Failed to download ${URL/https/http}.zsync"
@@ -1136,6 +1175,9 @@ function make_vm_config() {
             IMAGE_TYPE="iso";;
         windows)
             GUEST="windows"
+        IMAGE_TYPE="iso";;
+      windows-server)
+        GUEST="windows-server"
             IMAGE_TYPE="iso";;
         *)
             GUEST="linux"
@@ -1156,7 +1198,7 @@ guest_os="${GUEST}"
 disk_img="${VM_PATH}/disk.qcow2"
 ${IMAGE_TYPE}="${VM_PATH}/${IMAGE_FILE}"
 EOF
-        echo "Giving user execute permissions on ${CONF_FILE},"
+        echo "Giving user execute permissions on ${CONF_FILE}"
         chmod u+x "${CONF_FILE}"
         if [ -n "${ISO_FILE}" ]; then
             echo "fixed_iso=\"${VM_PATH}/${ISO_FILE}\"" >> "${CONF_FILE}"
@@ -1232,7 +1274,7 @@ EOF
           echo "disk_size=\"32G\"" >> "${CONF_FILE}"
         fi
         # Enable TPM for Windows 11
-        if [ "${OS}" == "windows" ] && [ "${RELEASE}" -ge 11 ]; then
+        if [ "${OS}" == "windows" ] && [ "${RELEASE}" == 11 ] || [ "${OS}" == "windows-server" ] && [ "${RELEASE}" == "2022" ]; then
             echo "tpm=\"on\"" >> "${CONF_FILE}"
             echo "secureboot=\"off\"" >> "${CONF_FILE}"
         fi
@@ -2625,6 +2667,88 @@ handle_curl_error() {
     return 1
 }
 
+function download_windows-server() {
+    # Download enterprise evaluation windows versions
+    local windows_version="$1"
+    local enterprise_type="$2"
+
+    local url="https://www.microsoft.com/en-us/evalcenter/download-$windows_version"
+
+    local iso_download_page_html="$(curl --silent --location --fail --proto =https --tlsv1.2 --http1.1 -- "$url")" || {
+        handle_curl_error $?
+        return $?
+    }
+
+    local CULTURE=""
+    local COUNTRY=""
+    local PRETTY_RELEASE=""
+
+    case "$RELEASE" in
+      "10-ltsc") PRETTY_RELEASE="10 LTSC";;
+      "2012-r2") PRETTY_RELEASE="2012 R2";;
+      *) PRETTY_RELEASE="$RELEASE";;
+    esac
+
+    case "$LANG" in
+      "English (Great Britain)")
+        CULTURE="en-gb"
+        COUNTRY="GB";;
+      "Chinese (Simplified)")
+        CULTURE="zh-cn"
+        COUNTRY="CN";;
+      "Chinese (Traditional)")
+        CULTURE="zh-tw"
+        COUNTRY="TW";;
+      "French")
+        CULTURE="fr-fr"
+        COUNTRY="FR";;
+      "German")
+        CULTURE="de-de"
+        COUNTRY="DE";;
+      "Italian")
+        CULTURE="it-it"
+        COUNTRY="IT";;
+      "Japanese")
+        CULTURE="ja-jp"
+        COUNTRY="JP";;
+      "Korean")
+        CULTURE="ko-kr"
+        COUNTRY="KR";;
+      "Portuguese (Brazil)")
+        CULTURE="pt-br"
+        COUNTRY="BR";;
+      "Spanish")
+        CULTURE="es-es"
+        COUNTRY="ES";;
+      "Russian")
+        CULTURE="ru-ru"
+        COUNTRY="RU";;
+      *)
+        CULTURE="en-us"
+        COUNTRY="US";;
+    esac
+
+    iso_download_links="$(echo "$iso_download_page_html" | grep -o "https://go.microsoft.com/fwlink/p/?LinkID=[0-9]\+&clcid=0x[0-9a-z]\+&culture=$CULTURE&country=$COUNTRY" | head -c 1024)"
+
+    case "$enterprise_type" in
+      # Select x64 LTSC download link
+      "ltsc") iso_download_link=$(echo "$iso_download_links" | head -n 4 | tail -n 1);;
+      *) iso_download_link="$iso_download_links";;
+    esac
+
+    iso_download_link="$(curl --silent --location --output /dev/null --silent --write-out "%{url_effective}" --head --fail --proto =https --tlsv1.2 --http1.1 -- "$iso_download_link")"
+
+    if [ "${COUNTRY}" != "US" ]; then
+        echo Downloading "$(pretty_name "${OS}")" "${PRETTY_RELEASE}" in "${LANG}" from "$iso_download_link"
+    else
+        echo Downloading "$(pretty_name "${OS}")" "${PRETTY_RELEASE}" from "$iso_download_link"
+    fi
+
+    FILE_NAME="${iso_download_link##*/}"
+    web_get "$iso_download_link" "${VM_PATH}" "${FILE_NAME}"
+    OS="windows-server"
+}
+
 function download_windows() {
     # Download newer consumer Windows versions from behind gated Microsoft API
     # This function aims to precisely emulate what Fido does down to the URL requests and HTTP headers (exceptions: updated user agent and referer adapts to Windows version instead of always being "windows11") but written in POSIX sh (with coreutils) and curl instead of PowerShell (also simplified to greatly reduce attack surface)
@@ -2666,7 +2790,7 @@ function download_windows() {
     # tr: Filter for only numerics to prevent HTTP parameter injection
     # head -c was recently added to POSIX: https://austingroupbugs.net/view.php?id=407
     local product_edition_id="$(echo "$iso_download_page_html" | grep -Eo '<option value="[0-9]+">Windows' | cut -d '"' -f 2 | head -n 1 | tr -cd '0-9' | head -c 16)"
-    echo " - Product edition ID: $product_edition_id"
+    # echo " - Product edition ID: $product_edition_id"
 
     # Permit Session ID
     # "org_id" is always the same value
@@ -2691,8 +2815,9 @@ function download_windows() {
     # Limit untrusted size for input validation
     language_skuid_table_html="$(echo "$language_skuid_table_html" | head -c 10240)"
     # tr: Filter for only alphanumerics or "-" to prevent HTTP parameter injection
-    local sku_id="$(echo "$language_skuid_table_html" | grep "English (United States)" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
-    echo " - SKU ID: $sku_id"
+    # tr: Filter for only alphanumerics or "-" to prevent HTTP parameter injection
+    local sku_id="$(echo "$language_skuid_table_html" | grep "${LANG}" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
+    # echo " - SKU ID: $sku_id"
 
     # Get ISO download link
     # If any request is going to be blocked by Microsoft it's always this last one (the previous requests always seem to succeed)
@@ -2705,6 +2830,12 @@ function download_windows() {
 
     local failed=0
 
+    if [ "${LANG}" == "English (United States)" ]; then
+        LANG="English"
+    fi
+
+    local HASH=$(echo "$iso_download_link_html" | sed 's/<tr><td>/\n<tr><td>/g' | grep "$LANG  64-bit" | grep -o -P '(?<=</td><td>).*(?=</td></tr>)')
+
     # Limit untrusted size for input validation
     iso_download_link_html="$(echo "$iso_download_link_html" | head -c 4096)"
 
@@ -2715,6 +2846,10 @@ function download_windows() {
     fi
 
     if echo "$iso_download_link_html" | grep -q "We are unable to complete your request at this time."; then
+        if [ "${show_iso_url}" == 1 ] || [ "${test_iso_url}" == 1 ]; then
+            echo " - Failed to get URL: Microsoft blocked the automated download request based on your IP address."
+            exit 1
+        fi
         echo " - Microsoft blocked the automated download request based on your IP address."
         failed=1
     fi
@@ -2738,16 +2873,41 @@ function download_windows() {
         return 1
     fi
 
-    echo " - Got latest ISO download link (valid for 24 hours): $iso_download_link"
+    if [ "${show_iso_url}" == 1 ]; then
+        echo -e "   Windows ${RELEASE} Download (valid for 24 hours):\n${iso_download_link}"
+        exit 0
+    elif [ "${test_iso_url}" == 1 ]; then
+        wget --spider "${iso_download_link}"
+        exit 0
+    fi
+
+    if [ "${LANG}" != "English International" ]; then
+        echo Downloading Windows "${RELEASE}" in "${LANG}" from "$iso_download_link"
+    else
+        echo Downloading Windows "${RELEASE}" from "$iso_download_link"
+    fi
 
     # Download ISO
     FILE_NAME="$(echo "$iso_download_link" | cut -d'?' -f1 | cut -d'/' -f5)"
     web_get "$iso_download_link" "${VM_PATH}" "${FILE_NAME}"
+    # Only Windows 11 hashes can be found directly from Microsoft's page.
+    if [ "${windows_version}" == 11 ]; then
+        check_hash "${FILE_NAME}" "${HASH}"
+    fi
 }
 
 function get_windows() {
-    echo "Downloading Windows ${RELEASE}..."
+    if [ "${RELEASE}" == "10-ltsc" ]; then
+        download_windows-server windows-10-enterprise ltsc
+    elif [ "${OS}" == "windows-server" ]; then
+        download_windows-server windows-server-"${RELEASE}"
+    else
     download_windows "${RELEASE}"
+    fi
+
+    if [ "${download_iso}" == 1 ]; then
+        exit 0
+    fi
 
     echo "Downloading VirtIO drivers..."
     web_get "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso" "${VM_PATH}"
