macos
Signed-off-by: zenobit <zenobit@disroot.org>

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -1781,11 +1781,21 @@ function get_lmde() {
     HASH=$(wget -q -O- "${URL}/sha256sum.txt" | grep "${ISO}" | cut_1)
     echo "${URL}/${ISO} ${HASH}"
 }
+#shellcheck disable=SC2004
+function generate_id() {
+    local macRecoveryID=""
+    local TYPE="${1}"
+    local valid_chars=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "A" "B" "C" "D" "E" "F")
+    for ((i=0; i<$TYPE; i++)); do
+        macRecoveryID+="${valid_chars[$((RANDOM % 16))]}"
+    done
+    echo "${macRecoveryID}"
+}
 
 function get_macos() {
     local BOARD_ID=""
     local CWD=""
-    local MACRECOVERY=""
+    local CHUNKCHECK=""
     local MLB="00000000000000000"
     local OS_TYPE="default"
 
@@ -1822,43 +1832,80 @@ function get_macos() {
             BOARD_ID="Mac-E43C1C25D4880AD6";;
         ventura)        #13
             BOARD_ID="Mac-BE088AF8C5EB4FA2";;
+      sonoma)
+        BOARD_ID="Mac-53FDB3D8DB8CA971";;
         *) echo "ERROR! Unknown release: ${RELEASE}"
            releases_macos
            exit 1;;
     esac
 
-    # Use a bundled macrecovery if possible
     CWD="$(dirname "${0}")"
-    if [ -x "${CWD}/macrecovery" ]; then
-        MACRECOVERY="${CWD}/macrecovery"
-    elif [ -x /usr/bin/macrecovery ]; then
-        MACRECOVERY="/usr/bin/macrecovery"
+    if [ -x "${CWD}/chunkcheck" ]; then
+        CHUNKCHECK="${CWD}/chunkcheck"
+    elif [ -x /usr/bin/chunkcheck ]; then
+        CHUNKCHECK="/usr/bin/chunkcheck"
     else
-        web_get "https://raw.githubusercontent.com/wimpysworld/quickemu/master/macrecovery" "${HOME}/.quickemu"
-        MACRECOVERY="python3 ${HOME}/.quickemu/macrecovery"
+        web_get "https://raw.githubusercontent.com/wimpysworld/quickemu/master/chunkcheck" "${HOME}/.quickemu"
+        CHUNKCHECK="${HOME}/.quickemu/chunkcheck"
     fi
 
-    if [ -z "${MACRECOVERY}" ]; then
-        echo "ERROR! Can not find a usable macrecovery."
+    if [ -z "${CHUNKCHECK}" ]; then
+        read -r "ERROR! Can not find chunkcheck. Will not be able to verify image. Proceed anyway?" skipVerification
+        if [ "${skipVerification,,}" != "y" ] && [ "${skipVerification,,}" != "yes" ]; then
         exit 1
+        fi
+        echo 'Skipping verification' && skipVerification=true
     fi
 
+    OpenCore_qcow2="https://github.com/kholia/OSX-KVM/raw/master/OpenCore/OpenCore.qcow2"
+    OVMF_CODE="https://github.com/kholia/OSX-KVM/raw/master/OVMF_CODE.fd"
+    OVMF_VARS="https://github.com/kholia/OSX-KVM/raw/master/OVMF_VARS-1920x1080.fd"
     # Get firmware
-    web_get "https://github.com/kholia/OSX-KVM/raw/master/OpenCore/OpenCore.qcow2" "${VM_PATH}"
-    web_get "https://github.com/kholia/OSX-KVM/raw/master/OVMF_CODE.fd" "${VM_PATH}"
+    local appleSession=$(curl -v -H "Host: osrecovery.apple.com" -H "Connection: close" -A "InternetRecovery/1.0" http://osrecovery.apple.com/ 2>&1 | tr ';' '\n' | awk -F'session=|;' '{print $2}' | grep 1)
+    local info=$(curl -s -X POST -H "Host: osrecovery.apple.com" -H "Connection: close" -A "InternetRecovery/1.0" -b "session=\"${appleSession}\"" -H "Content-Type: text/plain"\
+    -d $'cid='"$(generate_id 16)"$'\nsn='${MLB}$'\nbid='${BOARD_ID}$'\nk='"$(generate_id 64)"$'\nfg='"$(generate_id 64)"$'\nos='${OS_TYPE} \
+    http://osrecovery.apple.com/InstallationPayload/RecoveryImage | tr ' ' '\n')
+    local downloadLink=$(echo "$info" | grep 'oscdn' | grep 'dmg')
+    local downloadSession=$(echo "$info" | grep 'expires' | grep 'dmg')
+    local chunkListLink=$(echo "$info" | grep 'oscdn' | grep 'chunklist')
+    local chunkListSession=$(echo "$info" | grep 'expires' | grep 'chunklist')
+
+    if [ "${show_iso_url}" == 1 ]; then
+        echo -e "Recovery URL (inaccessible through normal browser):\n${downloadLink}\nChunklist (used for verifying the Recovery Image):\n${chunkListLink}\nFirmware URLs:\n${OpenCore_qcow2}\n${OVMF_CODE}\n${OVMF_VARS}"
+        exit 0
+    elif [ "${test_iso_url}" == 1 ]; then
+        wget --spider --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}" "${downloadLink}"
+        wget --spider --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}" "${chunkListLink}"
+        exit 0
+    elif [ "${download_iso}" == 1 ]; then
+        echo "Downloading macOS ${RELEASE} from ${downloadLink}"
+        web_get "${downloadLink}" "${VM_PATH}" RecoveryImage.dmg --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}"
+        curl --progress-bar "${chunkListLink}" -o RecoveryImage.chunklist --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}"
+        VM_PATH="$(pwd)"
+
+    else
+        echo "Downloading macOS firmware"
+        web_get "${OpenCore_qcow2}" "${VM_PATH}"
+        web_get "${OVMF_CODE}" "${VM_PATH}"
     if [ ! -e "${VM_PATH}/OVMF_VARS-1920x1080.fd" ]; then
-        web_get "https://github.com/kholia/OSX-KVM/raw/master/OVMF_VARS-1920x1080.fd" "${VM_PATH}"
+            web_get "${OVMF_VARS}" "${VM_PATH}"
     fi
 
     if [ ! -e "${VM_PATH}/RecoveryImage.chunklist" ]; then
-        echo "Downloading ${RELEASE}..."
-        ${MACRECOVERY} \
-            --board-id "${BOARD_ID}" \
-            --mlb "${MLB}" \
-            --os-type "${OS_TYPE}" \
-            --basename RecoveryImage \
-            --outdir "${VM_PATH}" \
-            download
+            echo "Downloading macOS ${RELEASE} from ${downloadLink}"
+            web_get "${downloadLink}" "${VM_PATH}" RecoveryImage.dmg --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${downloadSession}"
+            curl --progress-bar "${chunkListLink}" -o "${VM_PATH}/RecoveryImage.chunklist" --header "Host: oscdn.apple.com" --header "Connection: close" --header "User-Agent: InternetRecovery/1.0" --header "Cookie: AssetToken=${chunkListSession}"
+        fi
+    fi
+
+    if [ "$skipVerification" != true ]; then
+        if ! python3 "${CHUNKCHECK}" "${VM_PATH}" 2> /dev/null; then
+            echo "Verification failed."
+            exit 1
+        fi
+        echo "Verified macOS ${RELEASE} image using chunklist."
+    else
+        echo "Skipping verification of image."
     fi
 
     if [ -e "${VM_PATH}/RecoveryImage.dmg" ] && [ ! -e "${VM_PATH}/RecoveryImage.img" ]; then
@@ -1866,6 +1913,7 @@ function get_macos() {
         qemu-img convert "${VM_PATH}/RecoveryImage.dmg" -O raw "${VM_PATH}/RecoveryImage.img" 2>/dev/null
     fi
 
+    rm "${VM_PATH}/RecoveryImage.dmg" "${VM_PATH}/RecoveryImage.chunklist"
     make_vm_config RecoveryImage.img
 }
 
