few more d/l tweaks

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3086,12 +3086,14 @@ function download_windows_workstation() {
     local session_id=""
     local iso_download_page_html=""
     local product_edition_id=""
+    local language_skuid_table_cmd=""
     local language_skuid_table_html=""
     local sku_id=""
+    local iso_download_link_cmd=""
     local iso_download_link_html=""
     local iso_download_link=""
 
-    echo "Downloading Windows ${RELEASE} (${I18N})"
+    echo; echo "Downloading Windows ${RELEASE} (${I18N})"
     # This function is adapted from the Mido project:
     # https://github.com/ElliotKillick/Mido
     # Download newer consumer Windows versions from behind gated Microsoft API
@@ -3107,6 +3109,9 @@ function download_windows_workstation() {
     # Make log for dev analysis
     { echo; date; echo; echo "$url"; echo 
     } >  "/tmp/qe_win_dl_log.txt"
+
+    { echo "I18N Lang:"; echo; echo "$I18N"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     local user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
     session_id="$(uuidgen)"
@@ -3125,8 +3130,8 @@ function download_windows_workstation() {
         return $?
     }
 
-    { echo "iso_download_page_html"; echo; echo "$iso_download_page_html"; echo 
-    } >>  "/tmp/qe_win_dl_log.txt"
+    { echo; date; echo "iso_download_page_html:"; echo; echo "$iso_download_page_html"; echo ; echo "End of Page"; echo
+    } >  "/tmp/qe_win_dl_page_html.txt"
 
     echo -n " - Getting Product edition ID: "
     # tr: Filter for only numerics to prevent HTTP parameter injection
@@ -3149,6 +3154,9 @@ function download_windows_workstation() {
     # Extract everything after the last slash
     local url_segment_parameter="${url##*/}"
 
+    { echo "url_segment_parameter:"; echo; echo "$url_segment_parameter"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
+
     echo -n " - Getting language SKU ID: "
     # Get language -> skuID association table
     # SKU ID: This specifies the language of the ISO. We always use "English (United States)", however, the SKU for this changes with each Windows release
@@ -3159,8 +3167,16 @@ function download_windows_workstation() {
         return $?
     }
 
+    language_skuid_table_cmd="$(echo --silent --request POST --user-agent "$user_agent" --data "" --header "Accept:" --max-filesize 10K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=a8f8f489-4c7f-463a-9ca6-5cff94d8d041&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=getskuinformationbyproductedition&sessionId=$session_id&productEditionId=$product_edition_id&sdVersion=2")" || {
+
+    { echo; date; echo "language_skuid_table_html - FULL "; echo; echo "$language_skuid_table_html"; echo ; echo "End of Page"; echo
+    } >  "/tmp/qe_win_dl_lang_table full.txt"
+
     # Limit untrusted size for input validation
     language_skuid_table_html="$(echo "$language_skuid_table_html" | head -c 10240)"
+
+    { echo "language_skuid_table_cmd"; echo; echo "curl $language_skuid_table_cmd"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     { echo "language_skuid_table_html"; echo; echo "$language_skuid_table_html"; echo 
     } >>  "/tmp/qe_win_dl_log.txt"
@@ -3177,21 +3193,30 @@ function download_windows_workstation() {
     # Get ISO download link
     # If any request is going to be blocked by Microsoft it's always this last one (the previous requests always seem to succeed)
     # --referer: Required by Microsoft servers to allow request
-    iso_download_link_html="$(curl --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=GetProductDownloadLinksBySku&sessionId=$session_id&skuId=$sku_id&language=English&sdVersion=2")"
+    #iso_download_link_html="$(curl --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,$url_segment_parameter&query=&action=GetProductDownloadLinksBySku&sessionId=$session_id&skuId=$sku_id&language=English&sdVersion=2")"
+    iso_download_link_html="$(curl --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,${url_segment_parameter}&query=&action=GetProductDownloadLinksBySku&sessionId=${session_id}&skuId=${sku_id}&language=${I18N}&sdVersion=2")"
+    iso_download_link_cmd="$(echo --silent --request POST --user-agent "$user_agent" --data "" --referer "$url" --header "Accept:" --max-filesize 100K --fail --proto =https --tlsv1.2 --http1.1 -- "https://www.microsoft.com/en-US/api/controls/contentinclude/html?pageId=6e2a1789-ef16-4f27-a296-74ef7ef5d96b&host=www.microsoft.com&segments=software-download,${url_segment_parameter}&query=&action=GetProductDownloadLinksBySku&sessionId=${session_id}&skuId=${sku_id}&language=${I18N}&sdVersion=2")"
+
+    { echo "iso_download_link_cmd"; echo; echo "curl $iso_download_link_cmd"; echo 
+    } >>  "/tmp/qe_win_dl_log.txt"
 
     { echo "iso_download_link_html"; echo; echo "$iso_download_link_html"; echo 
     } >>  "/tmp/qe_win_dl_log.txt"
 
     local failed=0
-    #if ! [ "$iso_download_link_html" ]; then
-    if [[ ! $iso_download_link_html ]]; then
+    if ! [ "$iso_download_link_html" ]; then
         # This should only happen if there's been some change to how this API works
-        echo " - Microsoft servers gave us an empty response to our request for an automated download."
+        echo; echo " - Microsoft servers gave us an empty response to our request for an automated download."
         failed=1
     fi
 
     if echo "$iso_download_link_html" | grep -q "We are unable to complete your request at this time."; then
-        echo " - WARNING! Microsoft blocked the automated download request based on your IP address."
+        echo; echo " - WARNING! Microsoft blocked the automated download request based on your IP address."
+        failed=1
+    fi
+
+    if echo "$iso_download_link_html" | grep -q "We encountered a problem processing your request. Please try again later."; then
+        echo; echo " - WARNING! Microsoft blocked the automated download request based on your IP address."
         failed=1
     fi
 
@@ -3199,7 +3224,7 @@ function download_windows_workstation() {
         echo "   Manually download the Windows ${windows_version} ISO using a web browser from: ${url}"
         echo "   Save the downloaded ISO to: $(realpath "${VM_PATH}")"
         echo "   Update the config file to reference the downloaded ISO: ./${VM_PATH}.conf"
-        echo "   Continuing with the VM creation process..."
+        echo "   Continuing with the VM creation process..." ; echo
         return 1
     fi
 
@@ -3213,7 +3238,7 @@ function download_windows_workstation() {
 
     if ! [ "$iso_download_link" ]; then
         # This should only happen if there's been some change to the download endpoint web address
-        echo " - Microsoft servers gave us no download link to our request for an automated download. Please manually download this ISO in a web browser: $url"
+        echo " - Microsoft servers gave us no download link to our request for an automated download."; echo "   Please manually download this ISO in a web browser:"; echo "   $url"
         return 1
     fi
 
