feat: os_not_supported function

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3488,6 +3488,12 @@ os_supported() {
     fi
 }
 
+os_not_supported() {
+    echo -e "ERROR! ${OS} is not a supported OS.\n"
+    os_support | fold -s -w "$(tput cols)"
+    exit 1
+}
+
 function show_os_info() {
     local OS=""
     if [ -z "${1}" ]; then
