Add back the language array, change stylization of languages in list

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -201,6 +201,11 @@ function list_csv() {
         for OPTION in $(editions_"${OS}"); do
           echo "${DISPLAY_NAME},${OS},${RELEASE},${OPTION},${DOWNLOADER},${PNG},${SVG}"
         done
+      elif [[ "${OS}" == "windows"* ]]; then
+        "languages_${OS}"
+        for OPTION in "${LANGS[@]}"; do
+          echo "${DISPLAY_NAME},${OS},${RELEASE},${OPTION},${DOWNLOADER},${PNG},${SVG}"
+        done
       else
         echo "${DISPLAY_NAME},${OS},${RELEASE},,${DOWNLOADER},${PNG},${SVG}"
       fi
@@ -884,17 +889,20 @@ function releases_windows() {
     echo 8 10 10-ltsc 11
 }
 
-function editions_windows() {
+function languages_windows() {
     if [ "${RELEASE}" == 8 ]; then
-        echo Arabic Brazilian-Portuguese Bulgarian Chinese-Simplified Chinese-Traditional Chinese-Traditional-Hong-Kong Croatian Czech \
-        Danish Dutch English-United-States English-International Estonian Finnish French German Greek Hebrew Hungarian Italian Japanese \
-        Latvian Lithuanian Norwegian Polish Portuguese Romanian Russian Serbian-Latin Slovak Slovenian Spanish Swedish Thai Turkish Ukrainian
-    elif [ "${RELEASE}" == "10-ltsc" ]; then
-        echo English-United-States English-Great-Britain Chinese-Simplified Chinese-Traditional French German Italian Japanese Korean Portuguese-Brazil Spanish
-    else
-        echo Arabic Brazilian-Portuguese Bulgarian Chinese-Simplified Chinese-Traditional Croatian Czech Danish Dutch English \
-        English-International Estonian Finnish French French-Canadian German Greek Hebrew Hungarian Italian Japanese Korean Latvian \
-        Lithuanian Norwegian Polish Portuguese Romanian Russian Serbian-Latin Slovak Slovenian Spanish Spanish-Mexico Swedish Thai Turkish Ukrainian
+            LANGS=("Arabic" "Brazilian Portuguese" "Bulgarian" "Chinese (Simplified)" "Chinese (Traditional)" "Chinese (Traditional Hong Kong)" \
+            "Croatian" "Czech" "Danish" "Dutch" "English (United States)" "English International" "Estonian" "Finnish" "French" "German" "Greek" \
+            "Hebrew" "Hungarian" "Italian" "Japanese" "Latvian" "Lithuanian" "Norwegian" "Polish" "Portuguese" "Romanian" "Russian" "Serbian Latin" \
+            "Slovak" "Slovenian" "Spanish" "Swedish" "Thai" "Turkish" "Ukrainian")
+        elif [ "${RELEASE}" == "10-ltsc" ]; then
+            LANGS=("English (United States)" "English (Great Britain)" "Chinese (Simplified)" "Chinese (Traditional)" \
+            "French" "German" "Italian" "Japanese" "Korean" "Portuguese (Brazil)" "Spanish")
+        else
+            LANGS=("Arabic" "Brazilian Portuguese" "Bulgarian" "Chinese (Simplified)" "Chinese (Traditional)" "Croatian" "Czech" "Danish" "Dutch" \
+            "English (United States)" "English International" "Estonian" "Finnish" "French" "French Canadian" "German" "Greek" "Hebrew" "Hungarian" \
+            "Italian" "Japanese" "Korean" "Latvian" "Lithuanian" "Norwegian" "Polish" "Portuguese" "Romanian" "Russian" "Serbian Latin" "Slovak" \
+            "Slovenian" "Spanish" "Spanish (Mexico)" "Swedish" "Thai" "Turkish" "Ukrainian")
     fi
 }
 
@@ -902,8 +910,8 @@ function releases_windows-server() {
     echo 2012-r2 2016 2019 2022
 }
 
-function editions_windows-server() {
-    echo English-United-States Chinese-Simplified French German Italian Japanese Russian Spanish
+function languages_windows-server() {
+    LANGS=("English (United States)" "Chinese (Simplified)" "French" "German" "Italian" "Japanese" "Russian" "Spanish")
 }
 
 function releases_xerolinux() {
@@ -2650,7 +2658,6 @@ function download_windows-server() {
 
     local CULTURE=""
     local COUNTRY=""
-    local LANGUAGE=""
     local PRETTY_RELEASE=""
     
     case "$RELEASE" in
@@ -2660,55 +2667,43 @@ function download_windows-server() {
     esac
 
 
-    case "$EDITION" in
-        "English-Great-Britain")
+    case "$LANG" in
+        "English (Great Britain)")
             CULTURE="en-gb"
-            COUNTRY="GB"
-            LANGUAGE="English (Great Britain)";;
-        "Chinese-Simplified")
+            COUNTRY="GB";;
+        "Chinese (Simplified)")
             CULTURE="zh-cn"
-            COUNTRY="CN"
-            LANGUAGE="Chinese (Simplified)";;
-        "Chinese-Traditional")
+            COUNTRY="CN";;
+        "Chinese (Traditional)")
             CULTURE="zh-tw"
-            COUNTRY="TW"
-            LANGUAGE="Chinese (Traditional)";;
+            COUNTRY="TW";;
         "French")
             CULTURE="fr-fr"
-            COUNTRY="FR"
-            LANGUAGE="French";;
+            COUNTRY="FR";;
         "German")
             CULTURE="de-de"
-            COUNTRY="DE"
-            LANGUAGE="German";;
+            COUNTRY="DE";;
         "Italian")
             CULTURE="it-it"
-            COUNTRY="IT"
-            LANGUAGE="Italian";;
+            COUNTRY="IT";;
         "Japanese")
             CULTURE="ja-jp"
-            COUNTRY="JP"
-            LANGUAGE="Japanese";;
+            COUNTRY="JP";;
         "Korean")
             CULTURE="ko-kr"
-            COUNTRY="KR"
-            LANGUAGE="Korean";;
-        "Portuguese-Brazil")
+            COUNTRY="KR";;
+        "Portuguese (Brazil)")
             CULTURE="pt-br"
-            COUNTRY="BR"
-            LANGUAGE="Portuguese (Brazil)";;
+            COUNTRY="BR";;
         "Spanish")
             CULTURE="es-es"
-            COUNTRY="ES"
-            LANGUAGE="Spanish";;
+            COUNTRY="ES";;
         "Russian")
             CULTURE="ru-ru"
-            COUNTRY="RU"
-            LANGUAGE="Russian";;
+            COUNTRY="RU";;
         *)
             CULTURE="en-us"
-            COUNTRY="US"
-            ;;
+            COUNTRY="US";;
     esac
 
     iso_download_links="$(echo "$iso_download_page_html" | grep -o "https://go.microsoft.com/fwlink/p/?LinkID=[0-9]\+&clcid=0x[0-9a-z]\+&culture=$CULTURE&country=$COUNTRY" | head -c 1024)"
@@ -2722,7 +2717,7 @@ function download_windows-server() {
     iso_download_link="$(curl --silent --location --output /dev/null --silent --write-out "%{url_effective}" --head --fail --proto =https --tlsv1.2 --http1.1 -- "$iso_download_link")"
 
     if [ -n "${LANGUAGE}" ]; then
-        echo Downloading $(pretty_name "${OS}") ${PRETTY_RELEASE} in "${LANGUAGE}" from "$iso_download_link"
+        echo Downloading $(pretty_name "${OS}") ${PRETTY_RELEASE} in "${LANG}" from "$iso_download_link"
     else
         echo Downloading $(pretty_name "${OS}") ${PRETTY_RELEASE} from "$iso_download_link"
     fi
@@ -2796,15 +2791,10 @@ function download_windows() {
     }
 
     # Limit untrusted size for input validation
-    language_skuid_table_html="$(echo "$language_skuid_table_html" | head -c 10240 | tr -d '()')"
-
-    if [ "${2}" == "--find-languages" ]; then
-        echo "$language_skuid_table_html" | grep -o -P '(?<=&quot;}">).*(?=</option>)' | tr ' ' '-' | tr '\n' ' '
-        return 0
-    fi
+    language_skuid_table_html="$(echo "$language_skuid_table_html" | head -c 10240)"
 
     # tr: Filter for only alphanumerics or "-" to prevent HTTP parameter injection
-    local sku_id="$(echo "$language_skuid_table_html" | grep "${EDITION//-/ }" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
+    local sku_id="$(echo "$language_skuid_table_html" | grep "${LANG}" | sed 's/&quot;//g' | cut -d ',' -f 1  | cut -d ':' -f 2 | tr -cd '[:alnum:]-' | head -c 16)"
     # echo " - SKU ID: $sku_id"
 
     # Get ISO download link
@@ -2818,11 +2808,11 @@ function download_windows() {
 
     local failed=0
 
-    if [ "${EDITION}" == "English-United-States" ]; then
-        EDITION="English"
+    if [ "${LANG}" == "English (United States)" ]; then
+        LANG="English"
     fi
 
-    local HASH=$(echo "$iso_download_link_html" | sed 's/<tr><td>/\n<tr><td>/g' | tr -d '()' | grep "$EDITION  64-bit" | grep -o -P '(?<=</td><td>).*(?=</td></tr>)')
+    local HASH=$(echo "$iso_download_link_html" | sed 's/<tr><td>/\n<tr><td>/g' | grep "$LANG  64-bit" | grep -o -P '(?<=</td><td>).*(?=</td></tr>)')
 
     # Limit untrusted size for input validation
     iso_download_link_html="$(echo "$iso_download_link_html" | head -c 4096)"
@@ -2965,6 +2955,8 @@ if ((BASH_VERSINFO[0] < 4)); then
     exit 1
 fi
 
+LANGS=()
+
 if [ -n "${1}" ]; then
     OS="${1,,}"
     if [ "${OS}" == "list" ] || [ "${OS}" == "list_csv" ]; then
@@ -3014,8 +3006,6 @@ if [ -n "${2}" ]; then
                 done
                 exit 1
             fi
-        elif [ "${OS}" == "windows" ] || [ "${OS}" == "windows-server" ]; then
-            EDITION="English-International"
         else
             echo -en "ERROR! You must specify an edition.\n - Editions: "
             editions_"${OS}"
@@ -3042,14 +3032,7 @@ if [ -n "${2}" ]; then
 
 
         VM_PATH="${OS}-${RELEASE}-${EDITION}"
-        if [ "${OS}" == "windows" ] || [ "${OS}" == "windows-server" ]; then
-            if [ -z "${3}" ]; then
-                VM_PATH="${OS}-${RELEASE}"
-            fi
-            get_windows
-        else
-            create_vm "$("get_${OS}" "${EDITION}")"
-        fi
+        create_vm "$("get_${OS}" "${EDITION}")"
     elif [ "${OS}" == "macos" ]; then
         # macOS doesn't use create_vm()
         validate_release releases_macos
@@ -3067,6 +3050,22 @@ if [ -n "${2}" ]; then
         # deepin doesn't use create_vm()
         validate_release releases_deepin
         get_deepin
+    elif [[ "${OS}" == "windows"* ]]; then
+        LANG="English International"
+        "languages_${OS}"
+        if [ -n "${3}" ]; then
+            LANG="${3}"
+            if [[ ! ${LANGS[*]} =~ "${LANG}" ]]; then
+                echo -e "ERROR! ${LANG} is not a supported Windows language:\n"
+                for LANG in "${LANGS[@]}"; do
+                  echo -n "${LANG} "
+                done
+                exit 1
+            fi
+            VM_PATH="$(echo "${OS}-${RELEASE}-${LANG// /-}" | tr -d '()')"
+        fi
+        validate_release "releases_${OS}"
+        get_windows
     else
         validate_release "releases_${OS}"
         create_vm "$("get_${OS}")"
@@ -3096,6 +3095,12 @@ else
       *ubuntu*)
         echo -n " - Releases: "
         releases_ubuntu | sed -Ee 's/eol-\S+//g' # hide eol releases
+        ;;
+      *windows*)
+        echo -n " - Releases: "
+        "releases_${OS}"
+        echo -n " - Languages: "
+        "languages_${OS}" && echo "${LANGS[@]}"
         ;;
       *)
         echo -n " - Releases: "
